### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by jlndk** [panique/php-login-minimal#18]
Would be really nice and awesome, if you added this package to composer/packagist. It would make it so much easier to intergrate into exsisting projects. I really like how tiny this version is compared to your huge one.

**Comment by panique** [comment]
He, thanks, but you cannot "integrate" this into other scripts! It's made to build an application on top of it. Beside, people who are using composer will probably not use this simple "amateur" script.

Sorry, but i think this does not make sense here.

**Comment by peterkokot** [comment]
Hello, I think adding composer somehow would be a smart move because now, no one will find it on packagist.org that way.
