### ISSUE TITLE
A simple example

### ISSUE THREAD

**Issue by m-menon** [panique/php-login-minimal#20]
hi,

I am totally new to PHP but with some effort I managed to get the php-minimal login page working. Thanks a lot for your efforts. Can I have a simple example as to how / which parts of the code do I need to use in other pages to check if the user has logged in?

I just have couple of days of experience with php so please forgive for the ignorant question. I assume this is the code that i have to use in all the pages? Btw do I need to put in the require statements as well?

<pre>
// include the configs / constants for the database connection
require_once("config/db.php");

// load the login class
require_once("classes/Login.php");

// create a login object. when this object is created, it will do all login/logout stuff automatically
// so this single line handles the entire login process. in consequence, you can simply ...
$login = new Login();

// ... ask if we are logged in here:
if ($login->isUserLoggedIn() == true) {
    // the user is logged in. you can do whatever you want here.
    // for demonstration purposes, we simply show the "you are logged in" view.
    include("views/logged_in.php");

} else {
    // the user is not logged in. you can do whatever you want here.
    // for demonstration purposes, we simply show the "you are not logged in" view.
    include("views/not_logged_in.php");
}
</pre>

Thanks a ton,
rw

**Comment by panique** [comment]
Hey @m-menon 

welcome to the weird PHP-world :) ! First, I definitely recommend: Take this PHP thing easy and take your time to learn it, it will take months and maybe years before you will build real stuff, in the beginning it is mostly frustrating oh-my-god-why-does-it-do-this. Plus all the server-config stuff that make people really freak out.

May I ask you if PHP is your first language and you just started programming or are you just trying out PHP as a new languague ?

Anyway, the most easiest way is this: Simply copy the index.php and rename it to maybe page2.php or so and to whatever you want inside. Then let the user jump inside your application by simply making him/her click links to index.php, page2.php etc., like with .html files.

This is surely not a good way to do this, but it's easy to work with in the beginning.
Ah, and always keep the require(...)-stuff inside, as this will load all the necessary classes.

Have a great time
Chris

**Comment by m-menon** [comment]
hi panique,

Thanks a lot for the information. Yes, i totally understand the frustrating moments when being a newbie to php, and as a matter of fact to any programming language. As a matter of fact php gives even more ways to do things and that can sometime drive a person a wee bit crazy - on what's the correct approach to things :-)

I am not a serious web developer but I have dabbled in some html / css / javascript & jquery. And thanks for the easiest way but I am a little fussy about quality of code so I'd rather spend some more time and make my code more robust, readable and easy to maintain. So I was looking at ways to clearly separate out the authorization from html and other php code :)

So assuming that I have a html + php page called emprecords.php where I do certain tasks, Is the below an acceptable way? Or should I add a few lines to the beginning of the page and redirect them to login page of they have logged in? This way there will be more clarity in my code.

Each of my php page will have the following code

emprecords.php
<pre>
// include the configs / constants for the database connection
require_once("config/db.php");

// load the login class
require_once("classes/Login.php");

// create a login object. when this object is created, it will do all login/logout stuff automatically
// so this single line handles the entire login process. in consequence, you can simply ...
$login = new Login();

// ... ask if we are logged in here:
if ($login->isUserLoggedIn() == true) {
    // Show the Employee records and let the user do the CRUD on that because this user has         //logged in

} else {
    // take the user to the login page?
}
</pre>

Again thanks a lot for your time. Really appreciate it

M&M

**Comment by Oskii** [comment]
`if(isset($_SESSION['user_name]))` will tell you whether the user is logged in.

**Comment by mmendescortes** [comment]
the right way should be
```
// load the login class
require_once("classes/Login.php");

// create a login object
$login = new Login();

// here is what you want
if ($login->isUserLoggedIn() == true) {

    // here goes your view
    include("views/your_view.php");

} else {

    // here the fallback view
    include("views/not_logged_in.php");

}
```
