### ISSUE TITLE
Class doesn't exist

### ISSUE THREAD

**Issue by Sweganen** [panique/php-login-minimal#21]
Hello. I've installed it just the way you told me to but as soon as i try to log in or register i get this message:
"Fatal error: Class 'mysqli' not found in C:\Users\pontus.jarl\PhpstormProjects\loginSystem\classes\Login.php on line 55"

It says the same thing on register but then it says : 
 "Fatal error: Class 'mysqli' not found in C:\Users\pontus.jarl\PhpstormProjects\loginSystem\classes\Registration.php on line 69"
I tried the advanced one and that one worked flawless until i came to the mail thing as i dont really know how to fix the mail thing as i've never worked with smtp before. Either way. Thank you in advance.

**Comment by panique** [comment]
please simply follow the install tutorial and also have a look on the basics of PHP first.
