### ISSUE TITLE
Problems with session_start();

### ISSUE THREAD

**Issue by difelici** [panique/php-login-minimal#22]
Seems like there is a error with the  session_start(); when i insert the code:

 if (!isset($_SESSION)) {
    echo 'session not set';
} else {
    echo  print_r($_SESSION, true);
}

Aparently there is no session set, but when i insert session_start(); occurs another error : 
A session had already been started - ignoring session_start() 

Somebody please help me.

**Comment by panique** [comment]
He, have you installed and used the script like described in the install tutorial ? Have you checked the live-demo (where this error does not occur) ? Maybe your php-version is too new (or too old) or so ?

**Comment by difelici** [comment]
My php version is 5.5. I downloaded the demo version and inserted the code to test the session e and the same error ocurred

**Comment by difelici** [comment]
Thanks for answered me.  Yeah i  installed and used the script like described in the install tutorial. i have tried different options to solve the problem but its not working
