### ISSUE TITLE
Description not matching implementation?

### ISSUE THREAD

**Issue by coffear** [panique/php-login-minimal#25]
Within the read me you mention a bug that makes mySQL5 a requirement due to PDO issues.

Within the scripts however you are using mySQLi. Ideally the proper PDO functions should be used. This would also allow for the script to work with other database engines such as postgres with minimal changes.

**Comment by panique** [comment]
Feel free to do this! When the script was written years ago with the intention to be the most simple solution possible, then postgres had absolutly no do inside a super-minimal script, and PDO was too complicated for absolute beginners, that's why it was built like that :)
