### ISSUE TITLE
Package 'php5-mysql' has no installation candidate ubuntu 16.04

### ISSUE THREAD

**Issue by icejack** [panique/php-login-minimal#27]
Solved problem with Ubuntu 16.04

if you using tutorial: https://www.dev-metal.com/install-php-login-nets-1-minimal-login-script-ubuntu/

open terminal: **sudo apt-get install libapache2-mod-php7.0**

and retry **install sudo apt-get install mysql-server php7.0-mysql** is NOT use php5-mysql, because: E: Package 'php5-mysql' has no installation candidate ubuntu 16.04.

**Comment by panique** [comment]
As the title and the content clearly says, the tutorial is for Ubuntu 12.04 LTS, not 16.04, so it's a 4 year earlier version :)

The script was written in 2010-2013 when an install guide for 12.04 made sense. Sorry but when you want to install PHP7 then search for a tutorial.

**Comment by sayakpaul** [comment]
I installed PHP 5.6 first. Then used sudo apt-get install php5.6-mysql and it successfully got installed. I am using 16.04. I commented because i guess there are many like me who still find the 5.6 version a bit cozy and handy.

**Comment by icejack** [comment]
I will use your instructions. Return here 👍
