### ISSUE TITLE
unavailable domain

### ISSUE THREAD

**Issue by mohsenuss91** [panique/php-login-minimal#28]
http://ww1.php-login.net/
is for sale

**Comment by panique** [comment]
Okay, thanks, but where exactly do you see this link ?
FYI a year ago somebody has "stolen" the domain :/ so the project has to live without it now

**Comment by wopian** [comment]
@panique there's 2 links to php-login.net that redirect to it.

https://github.com/panique/php-login-minimal/blob/dd4ae407383da29e4701266bfb4c327038309497/index.php#L5
https://github.com/panique/php-login-minimal/blob/dd4ae407383da29e4701266bfb4c327038309497/register.php#L5

**Comment by panique** [comment]
Thanks a lot to your both, I've removed the link :)
