### ISSUE TITLE
Replace all mysqli query to PDO

### ISSUE THREAD

**Issue by the94air** [panique/php-login-minimal#31]
PDO is more secure can you add PDO to your php login repository or can i make an other repository for that?

**Comment by panique** [comment]
Hi, this project is not development anymore for 3+ years now, the reason for using mysqli was that this is the most simple and minimal possiblity to connect to mysql db, for sure PDO would be better, but as PDO was not a natively working thing in the PHP 5.3 era, we made this with mysqli.

Maybe you checkout the php-login-advanced or you try out HUGE ?
