### ISSUE TITLE
PHP Login Advanced?

### ISSUE THREAD

**Issue by blacksector** [panique/php-login-minimal#33]
Hey,

Was just wondering what happened to the PHP Login Advanced repository. I am currently using it in my project and was worried maybe there is a security hole? Or was it taken down because it is no longer maintained? Thanks!

**Comment by panique** [comment]
Hi, i just deleted the repo as it was simply too old and not well maintained and traffic was getting very low on the project. As far as i know there are no important security holes, but having such a project online for years without any updates might not be the best thing :)

There is HUGE (https://github.com/panique/huge) which is basically the much much improved version of php-login-advanced, so you have a nice alternative.

**Comment by blacksector** [comment]
I would just like to say thank you for all the hard work you have put into the project. And I see now, thank you so much! I might implement HUGE into my next project, not sure yet, thanks!

**Comment by panique** [comment]
:) Thanks too for the nice words!
