### ISSUE TITLE
Password saving method (Security issue)

### ISSUE THREAD

**Issue by i3130002** [panique/php-login-minimal#38]
Years ago I used this project to address a website login background but now that I know more about security I get that we must passwords as a Hash of (password+salt) PLUS saving the salt in another column in order to be able to verify user. 
If I am right about your code bellow([./classes/login.php](https://github.com/panique/php-login-minimal/blob/master/classes/Login.php)) :
![image](https://user-images.githubusercontent.com/11602376/51835642-53df3a80-2313-11e9-9b89-a2b03d612d7d.png)

In line 84 it checks the direct hash of the password with the saved one. Also in the database we have no salt column.

May I ask to put some time to fix it or please put an alert at the beginning of the readme so people don't use it as a prefect example or in real world ?

**Comment by i3130002** [comment]
My bad! As of further looking into the saved password I noticed that it combines them all together. 
for more reference one can visit [https://stackoverflow.com/questions/6832445/how-can-bcrypt-have-built-in-salts](https://stackoverflow.com/questions/6832445/how-can-bcrypt-have-built-in-salts)

**Comment by panique** [comment]
;)
